package(default_visibility = ["//visibility:public"])

py_library(
    name = "multihost",
    srcs = ["multihost.py"],
)

py_library(
    name = "multislice",
    srcs = ["multislice.py"],
    deps = [":multihost"],
)
