suite_name: PyTorch Llama 3.1 8B Optimized GCS Benchmark
num_repeats: 20

benchmarks:
  - generator: orbax.checkpoint._src.testing.benchmarks.pytorch_checkpoint_benchmark.PyTorchCheckpointBenchmark
    options:
      reference_checkpoint_path: "/mnt/gcs_bucket/checkpoints/llama3.1-8B-checkpoints/"
      metric_tracemalloc_enabled: [False]
      save_thread_count: [16]
      save_per_thread_copy_ahead_mb: [100]
      enable_async_save: [True]
      cache_staged_state_dict: [False]
      enable_gcs_connector: [False]
