package(default_visibility = ["//visibility:public"])

py_library(
    name = "multihost",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
    deps = ["//checkpoint/orbax/checkpoint/_src/multihost"],
)

py_library(
    name = "multislice",
    srcs = ["multislice.py"],
)
