package(default_visibility = ["//visibility:public"])

py_library(
    name = "registration",
    srcs = ["registration.py"],
    tags = ["nofixdeps"],
    deps = [
        "//checkpoint/orbax/checkpoint/_src/multihost",
    ],
)
