package(default_visibility = ["//visibility:public"])

py_library(
    name = "asyncio_utils",
    srcs = ["asyncio_utils.py"],
)

py_test(
    name = "asyncio_utils_test",
    srcs = ["asyncio_utils_test.py"],
    deps = [":asyncio_utils"],
)

py_library(
    name = "composite",
    srcs = ["composite.py"],
)

py_test(
    name = "composite_test",
    srcs = ["composite_test.py"],
    deps = [":composite"],
)
