package(default_visibility = ["//visibility:public"])

py_library(
    name = "save_decision_policy",
    srcs = ["save_decision_policy.py"],
    deps = ["//checkpoint/orbax/checkpoint/_src/metadata:checkpoint_info"],
)
